// ignore_for_file: file_names

import 'package:minoragain/models/Station.dart';

List<Station> sList = [
  Station(sName: "Rajiv Chowk"),
  Station(sName: "Hauz Khas"),
  Station(sName: "Kalkaji Mandir"),
  Station(sName: "Saket"),
  Station(sName: "Kashmiri Gate"),
  Station(sName: "IGI Terminal1"),
  Station(sName: "Qutub Minar"),
  Station(sName: "Chandini Chowk"),
  Station(sName: "AIIMS Delhi"),
  Station(sName: "Dwarka"),
  Station(sName: "Noida Electronic City"),
  Station(sName: "Botanical Garden"),
  Station(sName: "Huda City Center"),
  Station(sName: "Aerocity"),
  Station(sName: "Janak Puri"),
  Station(sName: "Rajauri Garden"),
  Station(sName: "Dhaula Kuan"),
  Station(sName: "Jamia Milia Islamia"),
  Station(sName: "Karol Bagh"),
  Station(sName: "Shahdra"),
  Station(sName: "Kirti Nagar"),
  Station(sName: "Ashok Vihar"),
  Station(sName: "Anand Vihar"),
  Station(sName: "Samaypur Badli"),
  Station(sName: "Yamuna Bank"),
  Station(sName: "Mandi House"),
  Station(sName: "Central Secretrait"),
  Station(sName: "Brigadier Hoshiyar Singh"),
  Station(sName: "IIT"),
  Station(sName: "IGI Terminal2"),
  Station(sName: "Vaishali"),
  Station(sName: "Lajpat Nagar"),
  Station(sName: "Azadpur"),
  Station(sName: "Akshardham Mandir"),
  Station(sName: "Inder Lok"),
  Station(sName: "Adarsh Nagar"),
  Station(sName: "Vidhan Sabha"),
  Station(sName: "New Bus Adda"),
  Station(sName: "New Delhi"),
  Station(sName: "Dilli Hart"),
  Station(sName: "Udyog Bhawan"),
  Station(sName: "Maurya Vihar"),
  Station(sName: "Ashok Park"),
  Station(sName: "Noida Sec.18"),
  Station(sName: "Okhla Vihar"),
  Station(sName: "Greater Kailash"),
  Station(sName: "Sultanpur"),
  Station(sName: "Raja Nahar Singh"),
  Station(sName: "Karkarduma"),
];

List<List<int>> vec = [
  [],
  [8, 23, 22, 9, 41],
  [22, 23, 8, 41, 9],
  [4],
  [3, 5],
  [4, 6],
  [5, 1],
  [1, 8],
  [7, 2, 1],
  [10, 38, 2, 1],
  [9, 11],
  [38, 22, 10, 12],
  [11, 13],
  [12, 28, 27, 14],
  [13, 15],
  [14, 16],
  [15, 17],
  [16],
  [20, 26],
  [27, 21],
  [21, 18],
  [19, 22, 26, 20],
  [2, 21, 11, 1],
  [2, 24, 1],
  [23, 25],
  [24, 26],
  [25, 21, 18],
  [13, 19],
  [29, 13],
  [38, 30, 28, 34],
  [31, 29],
  [32, 30],
  [33, 35, 31],
  [32],
  [29],
  [36, 32],
  [35, 37],
  [36, 39, 38],
  [37, 29, 9, 11],
  [37, 40],
  [42, 39, 41],
  [2, 40, 1],
  [43, 45, 40],
  [44, 42],
  [43],
  [1, 46, 42],
  [5],
  [48, 1],
  [49, 47, 25],
  [48],
];

Map<int, String> sInfo = {
  1: "Kashmiri Gate",
  3: "Samaypur Badli",
  4: "Adarsh Nagar",
  5: "Azadpur",
  6: "Vidhan Sabha",
  47: "Inder Lok",
  48: "Ashok Park",
  49: "Brigadire Hoshiyar Singh",
  45: "Shahadra",
  46: "New Bus Adda",
  25: "Rajauri Garden",
  24: "Kirti Nagar",
  26: "Janakpuri",
  23: "Karol Bagh",
  7: "Chandani Chowk",
  8: "New Delhi",
  2: "Rajiv Chowk",
  41: "Mandi House",
  40: "Yamuna Bank",
  42: "Karkarduma",
  43: "Anand Vihar",
  44: "Vaishali",
  39: "Akshardham",
  37: "Mayur Vihar",
  36: "Ashok Vihar",
  35: "Noida Sec.18",
  32: "Botanical Garden",
  33: "Noida Electronic City",
  18: "Dwarka",
  20: "IGI Terminal2",
  21: "Aerocity",
  22: "Dhaula Kuan",
  19: "IGI Terminal1",
  27: "IIT",
  10: "Udyog Bhawan",
  11: "Dilli Hart",
  12: "AIIMS",
  9: "Central Secretrait",
  38: "Lajpat Nagar",
  31: "Okhla Vihar",
  30: "Jamia Milia Islamia",
  29: "Kalkaji Mandir",
  28: "Greater Kailash",
  13: "Hauz Khas",
  14: "Saket",
  15: "Sultanpur",
  16: "Qutub Minar",
  17: "Huda City Center",
  34: "Raja Nahar Singh",
}; 


/* Map<String, String> sInfo = {
  ""
}; */

/* List<Transaction> tInfo = [
  Transaction(10.0, 25-05-2001, {"Source": "AIIMS", "Destination": "Hauz Khaz"}),
  Transaction(amount: 25, date: DateTime("25"), tdetails: tdetails)
]; */
